//
// Created by David on 2023. 05. 15..
//

#ifndef LABOR12A_CONSTANTS_H
#define LABOR12A_CONSTANTS_H

#define MEMORY_ALLOCATION_ERROR_CODE (-1)
#define MEMORY_ALLOCATION_ERROR_MESSAGE "Error when allocating memory\n"
#define FILE_OPENING_ERROR_CODE (-2)
#define FILE_OPENING_ERROR_MESSAGE "Error when opening file\n"
#define NULL_POINTER_EXCEPTION_ERROR_MESSAGE "NULL pointer exception\n"
#define NULL_POINTER_EXCEPTION_ERROR_CODE (-3)
#define INVALID_POSITION_MESSAGE "INVALID position\n"
#define FULL_MESSAGE "FULL\n"
#define EMPTY_MESSAGE "EMPTY\n"
#define NOT_FOUND_MESSAGE "NOT FOUND\n"

#endif //LABOR12A_CONSTANTS_H
